wgumenyuk/momentum

packages/client/src/internal/api/past-workouts.ts
packages/client/src/internal/api/workouts.ts
packages/server/src/api/v1/index.ts
packages/server/src/api/v1/past-workouts.ts
packages/server/src/api/v1/users.ts
packages/server/src/api/v1/workouts.ts
packages/server/src/services/past-workouts.ts
packages/server/src/services/workouts.ts

PR: [Enhancement] Workouts und Past Workouts nicht an /users anhängen (#261)

---

packages/shared/src/index.ts

[Feature] Fehlende Fehlercodes hinzufügen (#264)

---

packages/server/src/models/event.ts
packages/shared/src/index.ts

[Feature] Event-Modell definieren (#265)

---

packages/client/src/components/Timer/index.ts
packages/server/src/models/nutrition.ts
packages/shared/src/index.ts

feat: added nutritional information

---

packages/client/src/components/JwtContext/index.tsx
packages/client/src/main.tsx

[Feature] Context für dekodierten JWT-Payload implementieren (#276)

---

packages/client/src/components/JwtContext/index.tsx
packages/client/src/pages/auth/LoginPage.tsx
packages/client/src/pages/auth/RegisterPage.tsx

[Feature] Token-Check bei Aufruf von `/login` und `/register` (#275)

---

packages/client/src/components/JwtContext/index.tsx
packages/client/src/pages/ProfilePage.tsx

[Feature] useJwt() verwenden in ProfilePage (#279)

---

packages/client/src/internal/api/events.ts
packages/client/src/internal/api/index.ts
packages/server/src/api/v1/events.ts
packages/server/src/services/events.ts

PR: [Feature] Endpunkte für Events hinzufügen (#281)

---

packages/client/src/internal/api/events.ts
packages/server/src/api/v1/events.ts
packages/server/src/services/events.ts

PR: [Feature] Event-Service und -Endpunkt implementieren (#266)

---

packages/client/src/components/JwtContext/index.tsx
packages/server/src/types/koa/index.d.ts
packages/shared/src/index.ts

PR: [Enhancement] JWT-Payload in Shared verschieben (#290)

---

packages/client/src/components/JwtContext/index.tsx
packages/client/src/components/ProtectedRoute/index.tsx
packages/client/src/pages/auth/LoginPage.tsx
packages/client/src/pages/auth/LogoutPage.tsx
packages/client/src/pages/auth/RegisterPage.tsx

PR: [Bug] Logout leitet nicht zu Login weiter (#292)

---

package.json
packages/client/package.json
packages/client/src/index.css
packages/client/tailwind.config.js
pnpm-lock.yaml

feat: added new font to front end

---

packages/client/src/pages/ProfilePage.tsx

PR: [Enhancement] Ungeladenes Profil nicht rendern, wenn Fehler aufgetreten ist (#298)

---

packages/client/src/internal/api/users.ts
packages/server/src/api/v1/users.ts
packages/server/src/services/user.ts
packages/shared/src/index.ts

PR: [Feature] Service und API-Endpunkt zum Ändern des Display Names (#301)

---

packages/client/src/pages/ProfilePage.tsx

PR: [Feature] Input für den Display Name auf der Profil-Seite hinzufügen (#302)

---

packages/client/src/pages/ProfilePage.tsx

PR: [Feature] Card mit User-ID im Profil (#304)

---

packages/client/src/pages/auth/LogoutPage.tsx

<img
src="https://github.com/wgumenyuk/momentum/assets/50965068/f5ad9fdc-6f65-49b4-9f8c-4d36613f3bdc"
width="256px"
/>
Close: #293.

PR: [Enhancement] Refactor: Logout-Page (#293)

---

packages/server/src/services/social.ts

PR: [Bug] recipientId ist undefined beim Versenden einer Freundschaftsanfrage (#308)

---

packages/client/src/internal/api/friendships.ts
packages/client/src/pages/social/AddUser.tsx
packages/client/src/pages/social/Feed.tsx

PR: [Feature] Events bei Freundschaften erstellen (#267)

---

packages/server/src/api/v1/index.ts

[Feature] Exercises-Router registrieren (#297)

---

packages/client/src/components/FriendRequest/index.tsx
packages/client/src/internal/api/events.ts
packages/client/src/internal/api/friendships.ts
packages/client/src/pages/social/Feed.tsx
packages/server/src/api/v1/events.ts
packages/server/src/services/events.ts
packages/server/src/services/social.ts

PR: [Feature] Friend Request Event löschen, sobald akzeptiert (#313)

---

packages/server/src/services/auth.ts

feat: add token

---

packages/server/src/services/social.ts

[Feature] Freundschaftsanfragen blockieren, wenn Profil privat ist (#319)

---

packages/client/src/components/Countdown/index.tsx

PR: [Feature] Active Countdown Page (#285)

---

packages/client/src/components/Input/index.tsx

feat: deactivated spellcheck

---

packages/server/src/services/exercises.ts

fix: fixed mongodb querie in exercise api endpoint

---

packages/client/src/pages/ProfilePage.tsx
packages/server/src/services/exercises.ts

close: #330 
People nicht zu others sondern "Other users" geändert, klingt meiner Meinung nach professioneller

style: changed app message to users

---

packages/server/src/internal/seeder.ts

fix: fixed finalisation message for seeders

---

packages/client/src/pages/workout/AddWorkout.tsx

PR: [Feature] Workout löschen aus der Workout-Liste (#344)

---

packages/client/src/components/Countdown/index.tsx
packages/client/src/components/WorkoutContext/index.tsx
packages/client/src/main.tsx
packages/client/src/pages/WorkoutPage.tsx
packages/client/src/pages/workouts/AddExercise.tsx
packages/client/src/pages/workouts/AddWorkout.tsx
packages/client/src/pages/workouts/EditExercise.tsx
packages/client/src/pages/workouts/Filter.tsx
packages/client/src/pages/workouts/Workouts.tsx
packages/client/src/pages/workouts/index.tsx
packages/server/src/models/past-workout.ts
packages/shared/src/index.ts

PR: [Feature] Aktives Workout Page (#250)

---

packages/client/src/internal/api/past-workouts.ts
packages/client/src/pages/HomePage.tsx

PR: [Feature] Create Main Startseite nach Login (#207)

---

packages/client/src/components/Navigation/index.tsx

PR: [Bug] Navigation Highlight funktioniert mit Basepath nicht (#352)

---

packages/client/src/pages/ProfilePage.tsx

PR: [Bug] Weight ist im Profil NaN und kann nicht geändert werden (#356)
